#!/usr/bin/env python3
"""
Compile GLSL shaders to SPIR-V and generate a C++ header with byte arrays.

Usage:
    python compile_gltf_spirv.py [--glslang path/to/glslangValidator]

Requires glslangValidator in PATH (or --glslang).
Outputs gltf_vulkan_shaders.h in src/main/cpp/vulkan/.
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHADER_DIR = REPO_ROOT / "src" / "main" / "cpp" / "vulkan" / "shaders"
OUTPUT = REPO_ROOT / "src" / "main" / "cpp" / "vulkan" / "gltf_vulkan_shaders.h"
VERT_SRC = SHADER_DIR / "gltf_model.vert"
FRAG_SRC = SHADER_DIR / "gltf_model.frag"


def find_glslang() -> str:
    """Locate glslangValidator."""
    for name in ("glslangValidator", "glslang"):
        try:
            subprocess.run([name, "--version"], capture_output=True, check=True)
            return name
        except (subprocess.CalledProcessError, FileNotFoundError):
            continue
    raise RuntimeError(
        "glslangValidator not found. Set PATH or use --glslang."
    )


def compile_spirv(glslang: str, src: Path) -> bytes:
    """Compile a GLSL shader to SPIR-V binary and return the bytes."""
    with tempfile.NamedTemporaryFile(suffix=".spv") as output:
        subprocess.run([glslang, "-V", "-o", output.name, str(src)], check=True)
        output.seek(0)
        return output.read()


def to_c_array(name: str, data: bytes) -> str:
    """Convert binary SPIR-V to a uint32_t C array."""
    words = []
    for i in range(0, len(data), 4):
        w = int.from_bytes(data[i : i + 4], "little")
        words.append(f"    0x{w:08x}")

    # Group 6 per line for readability
    lines = []
    for i in range(0, len(words), 6):
        chunk = words[i : i + 6]
        lines.append("   " + ", ".join(chunk) + ",")

    body = "\n".join(lines).rstrip(",")
    size_name = name.replace("k", "k") + "Size"
    return (
        f"static constexpr uint32_t {name}[] = {{\n{body}\n}};\n"
        f"static constexpr size_t {size_name} = {len(data) // 4};\n"
    )


def generate_header(vert_spv: bytes, frag_spv: bytes) -> str:
    """Generate the complete header content."""
    return f"""// Auto-generated SPIR-V byte arrays. Do not edit.
// Regenerated by: scripts/compile_gltf_spirv.py
// Source shaders:
//   src/main/cpp/vulkan/shaders/gltf_model.vert
//   src/main/cpp/vulkan/shaders/gltf_model.frag
// Compiled at: {subprocess.check_output(['date', '-u']).decode().strip()}

#pragma once

#include <cstddef>
#include <cstdint>

namespace maplibre_gltf {{

{to_c_array("kVertSpirv", vert_spv)}
{to_c_array("kFragSpirv", frag_spv)}

}} // namespace maplibre_gltf
"""


def main():
    parser = argparse.ArgumentParser(description="Compile GLTF Vulkan shaders")
    parser.add_argument("--glslang", help="Path to glslangValidator")
    args = parser.parse_args()

    glslang = args.glslang or find_glslang()

    if not VERT_SRC.exists():
        sys.exit(f"Vertex shader not found: {VERT_SRC}")
    if not FRAG_SRC.exists():
        sys.exit(f"Fragment shader not found: {FRAG_SRC}")

    print(f"Compiling {VERT_SRC} ...")
    vert_spv = compile_spirv(glslang, VERT_SRC)
    print(f"  -> {len(vert_spv)} bytes")

    print(f"Compiling {FRAG_SRC} ...")
    frag_spv = compile_spirv(glslang, FRAG_SRC)
    print(f"  -> {len(frag_spv)} bytes")

    header = generate_header(vert_spv, frag_spv)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(header)
    print(f"Wrote {OUTPUT}")


if __name__ == "__main__":
    main()
