// Auto-generated SPIR-V byte arrays. Do not edit.
// Regenerated by: scripts/compile_gltf_spirv.py
// Source shaders:
//   src/main/cpp/vulkan/shaders/gltf_model.vert
//   src/main/cpp/vulkan/shaders/gltf_model.frag
// Compiled at: Thu Jul  9 10:14:01 UTC 2026

#pragma once

#include <cstddef>
#include <cstdint>

namespace maplibre_gltf {

static constexpr uint32_t kVertSpirv[] = {
    0x6573552f, 0x752f7372, 0x6d726573, 0x532f6361, 0x69647574, 0x6f72506f, 0x7463656a, 0x616d2f73,
    0x62696c70, 0x6e2d6572, 0x76697461, 0x6c702f65, 0x6f667461, 0x612f6d72, 0x6f72646e, 0x4d2f6469,
    0x694c7061, 0x47657262, 0x4c66746c, 0x72657961, 0x6372732f, 0x69616d2f, 0x70632f6e, 0x75762f70,
    0x6e616b6c, 0x6168732f, 0x73726564, 0x746c672f, 0x6f6d5f66, 0x2e6c6564, 0x74726576, 0x0000000a};
static constexpr size_t kVertSpirvSize = 31;

static constexpr uint32_t kFragSpirv[] = {
    0x6573552f, 0x752f7372, 0x6d726573, 0x532f6361, 0x69647574, 0x6f72506f, 0x7463656a, 0x616d2f73,
    0x62696c70, 0x6e2d6572, 0x76697461, 0x6c702f65, 0x6f667461, 0x612f6d72, 0x6f72646e, 0x4d2f6469,
    0x694c7061, 0x47657262, 0x4c66746c, 0x72657961, 0x6372732f, 0x69616d2f, 0x70632f6e, 0x75762f70,
    0x6e616b6c, 0x6168732f, 0x73726564, 0x746c672f, 0x6f6d5f66, 0x2e6c6564, 0x67617266, 0x0000000a};
static constexpr size_t kFragSpirvSize = 31;

} // namespace maplibre_gltf
